# Generated by Django 5.1 on 2024-10-07 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='clientaddress',
        ),
        migrations.RemoveField(
            model_name='client',
            name='clientaddress2',
        ),
        migrations.RemoveField(
            model_name='client',
            name='clientcity',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='supplieraddress',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='supplieraddress2',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='suppliercity',
        ),
    ]
